### ISSUE TITLE
PRIORITY 1 CHECKLIST

### ISSUE THREAD

**Issue by robertIanClarkson** [robertIanClarkson/SFSU-Connect#136]
PLZ ONLY EDIT THIS COMMENT

Priority 1:
1.Unregister User

- [x] User shall be able to browse all listings(https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/140)

- [x] User shall be able to create an account

- [x] User shall be able to search for listings based on category combined with text search(https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/140)

- [x] User shall be able to view each listing’s details (https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/137) (https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/138)

- [x] User shall be able to filter listings by price (https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/141)

2.Register User

- [x] User shall inherit all functional requirements of a unregistered user

- [x] User shall be able to send a message to a listing’s owner(https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/139)

- [x] User shall be able to login

- [x] User shall be able to post tutoring information(https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/119)

- [x] User shall be able to post items for sale(https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/119)

- [x] User shall be able to view their own items(https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/142)

- [x] User shall be able to view their own messages(https://github.com/CSC-648-SFSU/csc648-03-fa20-team01/issues/143)

3.Admin

- [x] Admin shall inherit all functional requirements of a registered user

- [x] Admin shall be able to remove postings the admin does not own

- [x] Admin shall be required to approve each listing before it is posted publicly

- [x] Admin shall be able to delete a registered user’s account
